### PR TITLE
Fix wrong height value in Flutter's TextStyle

### LINKED ISSUE #77: Wrong `height` value in Flutter's TextStyle
According to the Flutter documentation of the `TextStyle` class (https://api.flutter.dev/flutter/painting/TextStyle/height.html):
`height` - "The height of this text span, as a multiple of the font size."

Currently, when the user sets a `Line height` parameter of the font, the plugin just uses this value for the height of the `TextStyle`, which is wrong.

I propose to do the next:
1. `Line height unit == AUTO`: skip it in `TextStyle`;
2. `Line height unit == PIXELS`: set value as `lineHeight.value / fontSize` in `TextStyle`;
3. `Line height unit == PERCENT`: set value as `lineHeight.value / 100` in `TextStyle`.

### PR DESCRIPTION
**Pull request by ksokolovskyi**
Fixes #77

### CODE REVIEW

**Comment by ksokolovskyi** [comment]
@bernaferrari Please take a look at this PR.

**Comment by bernaferrari** [comment]
Sorry, I've been working a lot. I'll look today!!

**Comment by ksokolovskyi** [comment]
@bernaferrari Thanks a lot!

**Review by bernaferrari — APPROVED** [review]

**Comment by bernaferrari** [comment]
Thanks!!

**Pull request merged**
