### PR TITLE
Enhancements to Tailwind Class Generation and Figma Plugin Updates

### PR DESCRIPTION
**Pull request by Lampenbauer**
**Added Tailwind class names for serif and monospace fonts.**
When a user selects a specific font family in Figma and it matches the default font family defined in Tailwind, the plugin generates code using Tailwind utility classes.
- https://tailwindcss.com/docs/font-family
- https://imgur.com/39vYDyx (pay attention to the generated code in the plugin)

**Added a Tailwind class for overflow-hidden.**
When the „Clip content“ option is enabled for a frame or component in Figma, the plugin prints the „overflow-hidden“ class in the generated code.
- https://tailwindcss.com/docs/overflow
- https://www.delasign.com/blog/figma-frame-clip-content/
- https://imgur.com/6ruTd5m (can be seen at the end of the video)

**Improved CSS class name generation for custom color names.**
Previously, the plugin generated class names for custom color names in the format „hello-hello world“ if the Figma variable name was „hello/hello world.“ This resulted in two CSS class names.
With this code change, spaces are converted to dashes, ensuring that the Figma variable name „hello/hello world“ generates „hello-hello-world.“

**Added a Figma „documentonchange“ listener.**
The plugin code updates whenever something is updated in the Figma file.
- https://imgur.com/6ruTd5m (pay attention to the generated code in the plugin)

### CODE REVIEW

**Comment by Lampenbauer** [comment]
@davestewart @bernaferrari @mimshwright Have you been notified about this pull request? (It's my first ever PR on GitHub)

**Comment by bernaferrari** [comment]
I did! Thanks/sorry for the wait. I was traveling, then sick, then couldn't merge because github apparently thought there were conflicts, but now it is OK, just did. Thanks!

**Comment by Lampenbauer** [comment]
All good! I didn't want to cause any stress, I just didn't know if you had been notified as no reviewers or assignees were assigned to this PR. Cheers

**Comment by bernaferrari** [comment]
It is good, sometimes I forget. Thanks for the patience.

**Pull request merged**
