### PR TITLE
Add Tailwind support for horizontal-resize / hug

### PR DESCRIPTION
**Pull request by davestewart**
> Wasn't too sure what to name this PR; feel free to change.

### ✅ Hugging

This solves the `hug` part of #82, so:

- when horizontal resizing is set to `hug`, the Tailwind width class is omitted

### ⏸️ Wrapping

However, wrapping needs more work:

- for auto-layout `wrap`, the `flex-wrap` class will need to be added
- for wrapping alignment other than `top-*` I think `justify-*` needs to be changed to `content-*`
  - I think it should only be `justify` when `counterAxisAlignContent` is `SPACE_BETWEEN` ?
- support could also be added for `gap-x` and `gap-y`

I did some basic layouts just to check:

CleanShot 2024-07-02 at 22 36 25

The following is modified Tailwind code [in the playground](https://play.tailwindcss.com/Ofpvu2qLYv):

CleanShot 2024-07-02 at 22 32 52

```html
<!-- https://play.tailwindcss.com/Ofpvu2qLYv -->
<div class="flex items-center justify-center h-screen w-screen">
  <div class="flex flex-wrap justify-end content-end gap-6 w-56 h-44 p-3 outline-dashed outline-2">
    <div class="min-h-10 min-w-10 bg-cyan-100"></div>
    <div class="min-h-10 min-w-10 bg-blue-200"></div>
    <div class="min-h-10 min-w-10 bg-lime-400"></div>
    <div class="min-h-10 min-w-10 bg-teal-500"></div>
  </div>
</div>
```

Happy to continue looking at this, but very aware that I'm no TW expert so will happily take advice.

### CODE REVIEW

**Comment by bernaferrari** [comment]
I'm not *super* familiar with Figma's API right now, but you could try Figma's own inspect feature that shows the CSS, maybe it shows `content-` or whatever. Even though they have a custom renderer, Figma is 90% of the time CSS, so it should be easy to find a direct mapping between both.

**Comment by davestewart** [comment]
Ah, useful!

Are you happy to merge this, then I can look at wrapping in a new PR?

It would be really useful to have hugging not export as a fixed width in Tailwind.

**Comment by bernaferrari** [comment]
Yes, you are free to fix it on this PR too if you want, but if you prefer I can merge and wait for the next one :P

**Comment by davestewart** [comment]
I can't be sure I'll get to it in good time, so yes, please merge!

**Comment by davestewart** [comment]
> you could try Figma's own inspect feature that shows the CSS

Can also tinker with the CSS in the PLugin UI preview too:

CleanShot 2024-07-03 at 09 22 48

It would be cool here if the Tailwind classes could be used directly for Tailwind mode, vs just using the HTML renderer.

**Pull request merged**
